/**
 * Legal + safety copy. Plain, honest, store-review oriented. Not boilerplate
 * filler — written for THIS product (an AI companion, NOT therapy or medical
 * care). Review with counsel before production submission; the structure and
 * substance are here so the app is not auto-rejected on the common reasons.
 */
export const CONTACT_EMAIL = 'aise@gruve.events';
export const EFFECTIVE = '2026-05-17';
export const MIN_AGE = 17;

export type LegalDoc = 'privacy' | 'terms' | 'disclaimer';

export const LEGAL_TITLES: Record<LegalDoc, string> = {
  privacy: 'Privacy Policy',
  terms: 'Terms of Use',
  disclaimer: 'Important: What TrueSelf Is and Isn’t',
};

export const LEGAL: Record<LegalDoc, string[]> = {
  disclaimer: [
    `TrueSelf is a supportive AI companion. It is NOT therapy, NOT counseling, NOT a medical or mental-health service, and NOT a substitute for a licensed professional.`,
    `The companion does not diagnose, treat, or prescribe. In Health mode it offers general navigation and emotional support only — never a diagnosis, drug, or dosage. Always confirm anything specific with a licensed clinician or pharmacist.`,
    `If you are in crisis or may be in danger:`,
    `• If life is at risk, contact your local emergency number now.`,
    `• US: call or text 988 (Suicide & Crisis Lifeline).`,
    `• Nigeria: Nigeria Suicide Prevention Initiative, 0800 6577 4357.`,
    `TrueSelf can surface these resources but cannot provide emergency help itself.`,
    `Responses are generated by AI and may be wrong or incomplete. Use your own judgement and seek qualified human help for anything that matters.`,
    `By continuing you confirm you are at least ${MIN_AGE} years old and understand the above.`,
  ],
  privacy: [
    `Effective ${EFFECTIVE}. This policy explains what TrueSelf collects, why, and your choices. We wrote it to be readable, not to hide things.`,
    `WHAT WE STORE. Your name (optional), region (optional), an optional companion name, your messages with the companion, mood/energy check-ins, commitments, and the "garden" derived from them. This is the relationship — it only works because it remembers.`,
    `WHERE IT LIVES. In this build, data is stored locally on your device. If a hosted backend is enabled in future, sensitive content is encrypted at rest with strict access controls; you will be told before that changes.`,
    `WHAT WE DO NOT DO. We do not sell your data. We do not run ads. We do not use your conversations to train third-party models. Health and mental-health content is treated as the most sensitive tier.`,
    `AI PROCESSING. To reply, your message and relevant remembered context are sent to an AI model provider. Providers are bound by zero-retention / no-training terms before any production launch.`,
    `YOUR CONTROLS. You can export your data and permanently delete your account and all associated data from Settings at any time. Deletion is irreversible.`,
    `CHILDREN. TrueSelf is not for anyone under ${MIN_AGE}. We do not knowingly collect data from minors.`,
    `CONTACT. Questions or requests: ${CONTACT_EMAIL}.`,
  ],
  terms: [
    `Effective ${EFFECTIVE}. By using TrueSelf you agree to these terms.`,
    `NOT A PROFESSIONAL SERVICE. TrueSelf provides supportive, informational AI conversation. It is not therapy, medical, legal, or financial advice. See "What TrueSelf Is and Isn’t".`,
    `ELIGIBILITY. You must be at least ${MIN_AGE}. You are responsible for how you use guidance the companion offers.`,
    `ACCEPTABLE USE. Don’t use TrueSelf to harm yourself or others, to get instructions for dangerous acts, or for emergencies — contact emergency services instead.`,
    `NO WARRANTY. The service is provided "as is". AI output can be inaccurate. To the maximum extent permitted by law, we are not liable for decisions you make based on it. Nothing here limits liability that cannot be limited by law.`,
    `CHANGES. We may update these terms or the service. Material changes will be surfaced in-app.`,
    `TERMINATION. You may delete your account anytime in Settings. We may suspend access for misuse.`,
    `CONTACT. ${CONTACT_EMAIL}.`,
  ],
};
