/**
 * Legal + support copy. Single source — Privacy, Terms, and Help screens
 * read from here. Written for a career-coaching AI product (Cairn v3,
 * Career-only at launch per CEO plan 2026-05-26). The mental-health /
 * therapy framing has been removed; the not-professional-advice
 * disclaimer stays because every AI product needs it.
 *
 * Consent is folded INTO Terms (standard app onboarding pattern) — the
 * user accepts via the checkbox on the welcome onboarding's final step.
 * No separate consent screen.
 */
export const CONTACT_EMAIL = 'aise@gruve.events';
export const EFFECTIVE = '2026-05-26';
export const MIN_AGE = 17;

export type LegalDoc = 'privacy' | 'terms' | 'disclaimer';

export const LEGAL_TITLES: Record<LegalDoc, string> = {
  privacy: 'Privacy Policy',
  terms: 'Terms of Use',
  disclaimer: 'What Cairn Is and Isn’t',
};

export const LEGAL: Record<LegalDoc, string[]> = {
  disclaimer: [
    `Cairn is an AI career companion. It is NOT a licensed career counselor, NOT a recruiter, NOT a legal or financial advisor, and NOT a substitute for the judgment of a qualified human professional.`,
    `Your Cairn companion can research, plan, draft, and hold you to commitments. It cannot guarantee outcomes — not interviews, not offers, not promotions. Use your own judgment, and seek qualified human help for anything where the stakes are high.`,
    `Responses are generated by AI and may be wrong, incomplete, or out of date. Verify anything specific (compensation data, legal/tax/visa implications, company facts) with a primary source before acting on it.`,
    `If you are in crisis or may be in danger, contact your local emergency services. Cairn is not equipped to handle emergencies.`,
    `By using Cairn you confirm you are at least ${MIN_AGE} years old and understand the above.`,
  ],
  privacy: [
    `Effective ${EFFECTIVE}. This policy explains what Cairn collects, why, and your choices. Written to be readable, not to hide things.`,
    `WHAT WE STORE. Your name (optional), region (optional), an optional companion name, your messages with the companion, your goals and path, completed tasks, and the AI-built plan. This is the relationship — it only works because it remembers.`,
    `WHERE IT LIVES. In this build, data is stored locally on your device. If a hosted backend is enabled in future, sensitive content is encrypted at rest with strict access controls; you will be told before that changes.`,
    `WHAT WE DO NOT DO. We do not sell your data. We do not run ads. We do not use your conversations to train third-party models.`,
    `AI PROCESSING. To reply, your message and relevant remembered context are sent to an AI model provider. Providers are bound by zero-retention / no-training terms before any production launch.`,
    `YOUR CONTROLS. You can export your data and permanently delete your account and all associated data from Settings at any time. Deletion is irreversible.`,
    `GUEST BY DEFAULT. You can use Cairn without creating an account. If you later choose to sign in (e.g. to back up across devices or upgrade to Premium), we'll explain what changes before you do.`,
    `CHILDREN. Cairn is not for anyone under ${MIN_AGE}. We do not knowingly collect data from minors.`,
    `CONTACT. Questions or requests: ${CONTACT_EMAIL}.`,
  ],
  terms: [
    `Effective ${EFFECTIVE}. By using Cairn you agree to these terms.`,
    `WHAT TRUESELF IS. An AI career companion that helps you set goals, build a step-by-step path, and follow through. Plans, prompts, and feedback are generated by AI — see "What Cairn Is and Isn’t" for the full plain-English notice.`,
    `NOT A PROFESSIONAL SERVICE. Cairn provides supportive, informational AI guidance. It is not legal, medical, financial, tax, or licensed-counseling advice. Outcomes (interviews, offers, promotions) are never guaranteed.`,
    `ELIGIBILITY. You must be at least ${MIN_AGE}. You are responsible for how you use the guidance the companion offers.`,
    `ACCEPTABLE USE. Don’t use Cairn to harm yourself or others, to obtain instructions for dangerous acts, or for emergencies — contact emergency services instead.`,
    `NO WARRANTY. The service is provided "as is". AI output can be inaccurate. To the maximum extent permitted by law, we are not liable for decisions you make based on it. Nothing here limits liability that cannot be limited by law.`,
    `CHANGES. We may update these terms or the service. Material changes will be surfaced in-app.`,
    `TERMINATION. You may delete your account anytime in Settings. We may suspend access for misuse.`,
    `CONTACT. ${CONTACT_EMAIL}.`,
  ],
};
